apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-database.yaml
  - secret-application.yaml
  - pvc-database.yaml
  - pvc-application.yaml
  - database.yaml
  - application.yaml
  - backup.yaml
  - network-policy.yaml
  - ingress.yaml
