apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: colf-manager
  labels:
    app.kubernetes.io/name: colf-manager
    app.kubernetes.io/component: database-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: YOUR_STORAGE_CLASS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-data
  namespace: colf-manager
  labels:
    app.kubernetes.io/name: colf-manager
    app.kubernetes.io/component: database-backup-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: YOUR_STORAGE_CLASS
