apiVersion: v1
kind: Secret
metadata:
  name: colf-manager-application
  namespace: colf-manager
type: Opaque
stringData:
  app-secret: CHANGE_ME_LONG_RANDOM_AT_LEAST_32_CHARS
  admin-password: CHANGE_ME_AT_LEAST_12_CHARS_AND_A_NUMBER
